### ISSUE TITLE
openssl_suite.c: incomplete type EVP_MD_CTX

### ISSUE THREAD

**Issue by kalvdans** [WickrInc/wickr-crypto-c#1]
Tried to compile the source on Debian Stretch, and arrived at the following error:
<pre>
cd /home/chn/repo/wickr-crypto-c/build-unix/src/crypto && /usr/bin/cc   -I/home/chn/repo/wickr-crypto-c/build-unix/third-party/include -I/home/chn/repo/wickr-crypto-c/third-party/scrypt -I/home/chn/repo/wickr-crypto-c/third-party/bcrypt -I/home/chn/repo/wickr-crypto-c/third-party/protobuf-c -I/home/chn/repo/wickr-crypto-c/build-unix -I/home/chn/repo/wickr-crypto-c/src/crypto  -fPIC -O3 -DNDEBUG   -std=gnu99 -o CMakeFiles/wickr_crypto_lib.dir/openssl_suite.c.o   -c /home/chn/repo/wickr-crypto-c/src/crypto/openssl_suite.c
/home/chn/repo/wickr-crypto-c/src/crypto/openssl_suite.c: In function ‘__openssl_digest_sign_ctx_create’:
/home/chn/repo/wickr-crypto-c/src/crypto/openssl_suite.c:224:47: error: dereferencing pointer to incomplete type ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
     if (1 != EVP_DigestSignInit(ctx, NULL, ctx->digest, NULL, evp_signing_key)) {
                                               ^~
</pre>
Versions:
ii  libssl-dev:amd64                      1.1.0d-2                             amd64        Secure Sockets Layer toolkit - development files
gcc version 6.3.0 20170205 (Debian 6.3.0-6)

**Comment by tomleavy** [comment]
hey @kalvdans. Currently, the library requires OpenSSL 1.0.2

I haven't tested against 1.1.0 yet, but an upgrade of OpenSSL is planned once we evaluate the changes that are required

**Comment by tomleavy** [comment]
Opened a ticket to update OpenSSL. Closing this one. Thanks for the heads up!
