### ISSUE TITLE
Wickr Desktop Linux Issue by Darren Chaker

### ISSUE THREAD

**Issue by darrenchaker** [WickrInc/wickr-crypto-c#102]
Does anyone have issues with or knows of patches for Wickr on Linux? 
Thank you for your help, Darren Chaker

**Comment by tomleavy** [comment]
Hey Darren,

We are actively in the process of making Wickr work as a Snapcraft package. You go to https://support.wickr.com/hc/en-us and open a ticket so someone can let you know when it's available
