### ISSUE TITLE
snap package for centos is crashing on incoming message

### ISSUE THREAD

**Issue by qtlin** [WickrInc/wickr-crypto-c#123]
Since author of wickrme snap https://snapcraft.io/install/wickrme/centos tleavy appears here I would like to report that wickrme Qt tray icon code crashes application on incoming message when screen saver is active. Reproducible every time. Call stack trivially obtainable. For a quick tray icon error demonstration - right click on wickrme tray icon in snap on Ubuntu - observe About menu. Right click on wickrme tray icon in snap on CentOS/Fedora - nothing happens.

**Comment by tomleavy** [comment]
Hey @qtlin , this repository is strictly for the cryptography code used within the Wickr products, not the actual client. You should go to https://support.wickr.com so that we can fix your issue. Someone will be able to assist you there and make us an internal ticket so we can resolve your problem

**Comment by qtlin** [comment]
I know "repository is strictly for the cryptography code", but there is no way to bring this to senior dev management like yourself other then using this channel. This error has been reported to official support channel several years ago, it is supposedly in the dev queue, I am sure you have access to wickr ticket system to verify this yourself, but no changes in product are promised. You personally published CentOS instructions but have you actually verified complete functionality before advertising snap package for CentOS? Thank you for understanding my frustration.
