### ISSUE TITLE
Functions that receive user input?

### ISSUE THREAD

**Issue by qhdwns123** [WickrInc/wickr-crypto-c#17]
I would like to test my files as input.

Can someone help me?

test uses a fixed file.

I have difficulty because there is no guide.

**Comment by tomleavy** [comment]
hey @qhdwns123 can you give me more specifics about what you would like to do? Are you trying to generate test message data to test encryption / decryption or are you trying to test a specific function input for stability?

**Comment by qhdwns123** [comment]
@tomleavy

I want to test certain functions for stability.
I do not have a guide specifically for APIs.

**Comment by tomleavy** [comment]
sure no problem, there are a few functions that could take user input from the various versions of the UI that exist. Take a look at wickr_ctx.h, there are comments in the header that explain it's functionality, and that is the API that the Wickr apps use internally to interact with this library

**Comment by qhdwns123** [comment]
Have you ever made a fuzzing source for stability testing?

**Comment by tomleavy** [comment]
I have not personally done that, but others have run a fuzzing utility against the code before. Any contributions would be appreciated since it's something I've been looking to get into CI automation. I would like to use AFL

**Comment by qhdwns123** [comment]
@ tomleavy

In general, the AFL runs in a binary environment.

I think you should use libfuzzer for testing.

I'm not a Wickr developer, so I think testing will be difficult right now.

I will take a look if I have spare time.
