### ISSUE TITLE
header links in README are broken

### ISSUE THREAD

**Issue by justinTM** [WickrInc/wickr-crypto-c#170]
**current** (broken):
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/crypto/crypto_engine.h
**proposed**:
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/crypto_engine.h

**current** (broken):
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/crypto/openssl_suite.h
**proposed**:
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/openssl_suite.h

**current** (broken):
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/crypto/protocol.h
**proposed**:
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/protocol.h

**current** (broken):
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/crypto/wickr_ctx.h
**proposed**:
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/wickr_ctx.h

**current** (broken):
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/crypto/stream_cipher.h
**proposed**:
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/stream_ctx.h
-- or --
https://github.com/WickrInc/wickr-crypto-c/blob/master/src/wickrcrypto/include/wickrcrypto/stream_iv.h

**Comment by tomleavy** [comment]
#168 also is a readme problem, BUILD_TESTS should be -DBUILD_TESTS

**Comment by tomleavy** [comment]
Thanks for pointing this out!
