### ISSUE TITLE
Wickr Desktop Messenger?

### ISSUE THREAD

**Issue by baimafeima** [WickrInc/wickr-crypto-c#39]
Where do I find the source code for your desktop messaging application?

**Comment by tomleavy** [comment]
Hey @baimafeima, the code in this repo represents the implementation of the Wickr messaging protocol that is used by all of our clients, including the desktop messenger client. The source of the full desktop application is not available on GitHub at this time. You can check out our blog for updates on our open source initiatives as they become available or email us at crypto@wickr.com for more info.

**Comment by baimafeima** [comment]
@tomleavy Thanks for the updates. Looking forward to eventually seeing the full desktop application available on GitHub. This would be a prerequisite for having it evaluated to be added to the repositories of many operating systems and in turn would increase exposure to many potential users.

**Comment by baimafeima** [comment]
So there is Wire, Ring, Tox, Riot, Telegram, and most recently Signal with desktop applications for Linux-based operating systems, all open source and easily available via the software centers. It's about time to do the same for Wickr.

**Comment by qtlin** [comment]
to make matters worse, Wickr on Linux reliably works only Ubuntu and its derivatives.
they chose to use custom Qt build which is not compatible with everything else.
