### ISSUE TITLE
Wickr Wiping Question by Darren Chaker

### ISSUE THREAD

**Issue by darrenchaker** [WickrInc/wickr-crypto-c#59]
I am a long time user of [Wickr](https://www.wickr.com/personal) and recommend it to people who want serious privacy, most often where industrial espionage is concerned. A few months ago Wickr updated the app, but did not include its wiping option (wipes deleted data from phone with secure algorithm)  in the free version. Does anyone know if Wickr intends to put the wiping option back into a future version, or why it was removed in the first place?  Thank you for your time answering this question. Best, Darren Chaker.

**Comment by tomleavy** [comment]
Hey @darrenchaker , keeping this GitHub repo just about the crypto code itself. For sure send an email over to support@wickr.com so they can help keep you notified about the feature
